# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "riparian"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ken-ichi Ueda"]
  s.date = "2012-10-11"
  s.description = "Basically just a handful of models to make handling workflows and asynchronous server-side tasks a little easier."
  s.email = "kenichi.ueda@gmail.com"
  s.extra_rdoc_files = [
    "README",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "MIT-LICENSE",
    "README",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/app/models/flow_task.rb",
    "lib/app/models/flow_task_input.rb",
    "lib/app/models/flow_task_output.rb",
    "lib/app/models/flow_task_resource.rb",
    "lib/generators/USAGE",
    "lib/generators/riparian_generator.rb",
    "lib/generators/templates/flow_tasks_controller.rb",
    "lib/generators/templates/flow_tasks_helper.rb",
    "lib/generators/templates/migration.rb",
    "lib/generators/templates/views/flow_tasks/_delayed_progress.html.haml",
    "lib/generators/templates/views/flow_tasks/index.html.haml",
    "lib/generators/templates/views/flow_tasks/run.html.haml",
    "lib/generators/templates/views/flow_tasks/show.html.haml",
    "lib/riparian.rb",
    "riparian.gemspec",
    "test/database.yml",
    "test/flow_task_resource_test.rb",
    "test/flow_task_test.rb",
    "test/riparian_test.rb",
    "test/schema.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/kueda/riparian"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "DelayedJob-based workflow system."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["> 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, ["> 3.0.0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<delayed_job>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["> 3.0.0"])
      s.add_dependency(%q<activesupport>, ["> 3.0.0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<delayed_job>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["> 3.0.0"])
    s.add_dependency(%q<activesupport>, ["> 3.0.0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<delayed_job>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

